RewriteEngine On

RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/registro_sorteos/(.*)$ ws://192.168.2.91:8034$1 [P,L]

ProxyPass /registro_sorteos/ http://192.168.2.91:8034
ProxyPassReverse /registro_sorteos/ http://192.168.2.91:8034
